import type { ChartTemplate } from './types';
import { DS } from './types';

/* ═══════════════════════════════════════════════════════
   Built-in Chart Templates
   ═══════════════════════════════════════════════════════ */

export const BUILT_IN_TEMPLATES: ChartTemplate[] = [
  {
    id: 'tpl-bar-basic',
    name: 'Столбчатый базовый',
    description: 'Простая столбчатая диаграмма с одним рядом',
    icon: '📊',
    builtIn: true,
    config: {
      title: 'Столбчатая диаграмма',
      titleFontSize: 14,
      titleAlign: 'center',
      canvasW: 800,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'bar', color: DS.palette[0], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
      ],
      legendPosition: 'top',
      legendFontSize: 10,
      y1: { label: '', fontSize: 10, labelFontSize: 11, min: 'auto', max: 'auto', showGrid: true, gridStyle: 'dashed' },
    },
  },
  {
    id: 'tpl-line-multi',
    name: 'Линейный мульти',
    description: 'Несколько линейных рядов с маркерами',
    icon: '📈',
    builtIn: true,
    config: {
      title: 'Линейная диаграмма',
      titleFontSize: 14,
      titleAlign: 'center',
      canvasW: 800,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'line', color: DS.palette[0], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
        { id: 's2', name: '', type: 'line', color: DS.palette[1], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
      ],
      legendPosition: 'top',
      legendFontSize: 10,
      y1: { label: '', fontSize: 10, labelFontSize: 11, min: 'auto', max: 'auto', showGrid: true, gridStyle: 'dashed' },
    },
  },
  {
    id: 'tpl-area-gradient',
    name: 'Область с заливкой',
    description: 'Area chart с прозрачной заливкой',
    icon: '📉',
    builtIn: true,
    config: {
      title: 'Область',
      titleFontSize: 14,
      titleAlign: 'left',
      canvasW: 800,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'area', color: DS.palette[4], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
      ],
      legendPosition: 'hidden',
      y1: { label: '', fontSize: 10, labelFontSize: 11, min: 'auto', max: 'auto', showGrid: true, gridStyle: 'dashed' },
    },
  },
  {
    id: 'tpl-pie',
    name: 'Круговая',
    description: 'Pie chart для долей',
    icon: '🥧',
    builtIn: true,
    config: {
      title: 'Структура',
      titleFontSize: 14,
      titleAlign: 'center',
      canvasW: 600,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'pie', color: DS.palette[0], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
      ],
      legendPosition: 'bottom',
      legendFontSize: 10,
    },
  },
  {
    id: 'tpl-donut',
    name: 'Кольцевая',
    description: 'Donut chart для долей',
    icon: '🍩',
    builtIn: true,
    config: {
      title: 'Распределение',
      titleFontSize: 14,
      titleAlign: 'center',
      canvasW: 600,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'donut', color: DS.palette[3], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
      ],
      legendPosition: 'bottom',
      legendFontSize: 10,
    },
  },
  {
    id: 'tpl-combo-bar-line',
    name: 'Комбо: Bar + Line',
    description: 'Столбцы + линия на двух осях',
    icon: '📊',
    builtIn: true,
    config: {
      title: 'Комбинированный',
      titleFontSize: 14,
      titleAlign: 'center',
      canvasW: 800,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'bar', color: DS.palette[0], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
        { id: 's2', name: '', type: 'line', color: DS.palette[6], yAxis: 'y2', visible: true, strokeWidth: 2, showDataLabels: true, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'badge' },
      ],
      legendPosition: 'top',
      legendFontSize: 10,
      y1: { label: 'Значение', fontSize: 10, labelFontSize: 11, min: 'auto', max: 'auto', showGrid: true, gridStyle: 'dashed' },
      y2: { label: '%', fontSize: 10, labelFontSize: 11, min: 'auto', max: 'auto', showGrid: false, gridStyle: 'dashed' },
    },
  },
  {
    id: 'tpl-scatter',
    name: 'Точечный',
    description: 'Scatter plot для корреляции',
    icon: '🔵',
    builtIn: true,
    config: {
      title: 'Точечная диаграмма',
      titleFontSize: 14,
      titleAlign: 'center',
      canvasW: 600,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'scatter', color: DS.palette[0], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
      ],
      legendPosition: 'hidden',
      y1: { label: '', fontSize: 10, labelFontSize: 11, min: 'auto', max: 'auto', showGrid: true, gridStyle: 'dashed' },
    },
  },
  {
    id: 'tpl-bar-labels',
    name: 'Столбцы с подписями',
    description: 'Столбчатый с data labels в плашках',
    icon: '🏷️',
    builtIn: true,
    config: {
      title: 'Показатели',
      titleFontSize: 14,
      titleAlign: 'left',
      canvasW: 800,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'bar', color: DS.palette[0], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: true, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'badge' },
        { id: 's2', name: '', type: 'bar', color: DS.palette[1], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: true, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'badge' },
      ],
      legendPosition: 'top',
      legendFontSize: 10,
      y1: { label: '', fontSize: 10, labelFontSize: 11, min: 'auto', max: 'auto', showGrid: true, gridStyle: 'dashed' },
    },
  },
  {
    id: 'tpl-stacked-bar',
    name: 'Stacked Bar',
    description: 'Столбчатая с накоплением',
    icon: '📊',
    builtIn: true,
    config: {
      title: 'Структура показателей',
      titleFontSize: 14,
      titleAlign: 'center',
      canvasW: 800,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'stacked-bar', color: DS.palette[0], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
        { id: 's2', name: '', type: 'stacked-bar', color: DS.palette[1], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
        { id: 's3', name: '', type: 'stacked-bar', color: DS.palette[3], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
      ],
      legendPosition: 'top',
      legendFontSize: 10,
      y1: { label: '', fontSize: 10, labelFontSize: 11, min: 'auto', max: 'auto', showGrid: true, gridStyle: 'dashed' },
    },
  },
  {
    id: 'tpl-bar-horizontal',
    name: 'Горизонтальный Bar',
    description: 'Горизонтальная столбчатая диаграмма',
    icon: '📊',
    builtIn: true,
    config: {
      title: 'Рейтинг',
      titleFontSize: 14,
      titleAlign: 'left',
      canvasW: 800,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'bar-h', color: DS.palette[0], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
      ],
      legendPosition: 'hidden',
      y1: { label: '', fontSize: 10, labelFontSize: 11, min: 'auto', max: 'auto', showGrid: true, gridStyle: 'dashed' },
    },
  },
  {
    id: 'tpl-radar',
    name: 'Радар',
    description: 'Радарная (паутинная) диаграмма для сравнения нескольких показателей',
    icon: '🕸️',
    builtIn: true,
    config: {
      title: 'Радар',
      titleFontSize: 14,
      titleAlign: 'center',
      canvasW: 600,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'radar', color: DS.palette[0], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
        { id: 's2', name: '', type: 'radar', color: DS.palette[1], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
      ],
      legendPosition: 'top',
      legendFontSize: 10,
    },
  },
  {
    id: 'tpl-waterfall',
    name: 'Водопад',
    description: 'Каскадная диаграмма для анализа приращений (P&L bridge)',
    icon: '🌊',
    builtIn: true,
    config: {
      title: 'Водопадная диаграмма',
      titleFontSize: 14,
      titleAlign: 'center',
      canvasW: 800,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'waterfall', color: DS.palette[0], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
      ],
      legendPosition: 'hidden',
      y1: { label: '', fontSize: 10, labelFontSize: 11, min: 'auto', max: 'auto', showGrid: true, gridStyle: 'dashed' },
    },
  },
  {
    id: 'tpl-funnel',
    name: 'Воронка',
    description: 'Воронка продаж / конверсий',
    icon: '🔽',
    builtIn: true,
    config: {
      title: 'Воронка',
      titleFontSize: 14,
      titleAlign: 'center',
      canvasW: 600,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'funnel', color: DS.palette[0], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
      ],
      legendPosition: 'hidden',
    },
  },
  {
    id: 'tpl-treemap',
    name: 'Древовидная',
    description: 'Treemap для визуализации пропорций',
    icon: '🟩',
    builtIn: true,
    config: {
      title: 'Структура',
      titleFontSize: 14,
      titleAlign: 'center',
      canvasW: 700,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'treemap', color: DS.palette[0], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
      ],
      legendPosition: 'hidden',
    },
  },
  {
    id: 'tpl-gauge',
    name: 'Спидометр',
    description: 'Gauge для отображения одного значения (KPI)',
    icon: '🎯',
    builtIn: true,
    config: {
      title: 'KPI',
      titleFontSize: 14,
      titleAlign: 'center',
      canvasW: 400,
      canvasH: 320,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'gauge', color: DS.palette[0], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
      ],
      legendPosition: 'hidden',
    },
  },
  {
    id: 'tpl-heatmap',
    name: 'Тепловая карта',
    description: 'Heatmap для матричного сравнения показателей по периодам',
    icon: '🟥',
    builtIn: true,
    config: {
      title: 'Тепловая карта',
      titleFontSize: 14,
      titleAlign: 'center',
      canvasW: 800,
      canvasH: 480,
      showBackground: true,
      series: [
        { id: 's1', name: '', type: 'heatmap', color: DS.palette[0], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
        { id: 's2', name: '', type: 'heatmap', color: DS.palette[1], yAxis: 'y1', visible: true, strokeWidth: 2, showDataLabels: false, dataLabelFontSize: 9, dataLabelColor: '', dataLabelStyle: 'plain' },
      ],
      legendPosition: 'hidden',
    },
  },
];